# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-13 06:17
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assignment_id', models.UUIDField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='OPEN', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('choices_id', models.AutoField(primary_key=True, serialize=False)),
                ('seq', models.IntegerField()),
                ('choice', models.CharField(max_length=1000)),
                ('anwser', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('results_id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('completed_date', models.DateTimeField(default=datetime.datetime.now)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.Assignment')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('due_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.Session'),
        ),
        migrations.AddField(
            model_name='choices',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.Question'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.Session'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
