# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-22 06:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_auto_20180413_0136'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultDetails',
            fields=[
                ('results_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_correct', models.BooleanField()),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.Assignment')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.Question')),
            ],
        ),
    ]
